a = input("Digite algo: ")
print(f"O texto primitivo: {a} é:", type(a))
print(f"O texto primitivo: {a} é um espaço?", a.isspace())
print(f"O texto primitivo: {a} é um número?", a.isnumeric())
print(f"O texto primitivo: {a} é alfabético?", a.isalpha())
print(f"O texto primitivo: {a} é alfanumérico?", a.isalnum())
print(f"O texto primitivo: {a} é maiúsculo?", a.isupper())
print(f"O texto primitivo: {a} é minúsculo?", a.islower())
print(f"O texto de {a} capitalizado?", a.istitle())
